### ISSUE TITLE
Include in Debian?

### ISSUE THREAD

**Issue by olebole** [kernsuite-debian/miriad#1]
Miriad seems to be suitable for inclusion in Debian, and it is also packaged by [Scisoft](http://www.eso.org/sci/software/scisoft/Scisoft-contents.html) and referenced by [ASCL](http://ascl.net/1106.007).
From the dependencies, only two things are problematic here:
* pgplot5 (may be replaced by giza-dev)
* rpfits (is completely unused AFAIK).

Would you mind to remove these dependencies? Then, it should be no problem to make a proper DFSG-free package out of it and include it in Debian.

**Comment by gijzelaerr** [comment]
in theory i have no objects, but I don't know how much work it is. First we need to just get this package to work, and that already seems to require quite some effort since they assume you run in from the build folder. probably we need to patch it up here and the to let it look for all the files in the proper system installed locations.

**Comment by gijzelaerr** [comment]
btw personally i prefer to keep all the packaging related issued in the packaging repo:

https://github.com/kernsuite/packaging/issues

We have quite some repos here on github now, and i think it gets messy and hard to find issues if we have so many issue trackers. I usually just disable the issue trackers for all the debian repo's but i forget that for this one.

**Comment by olebole** [comment]
Yea, I had a bit more detailed look: directories should be a bit adjusted; `giza-dev` works well. Potential problem is first the huge number of executables, many of them with rather common names which probably have one or the other conflict with other packages (even astro related). Then there is linpack included; this is probably free, but one would need to check the license -- or switch to lapack. Linpack is so much 70s! Wondering why they didn't do the step.
And then there are two versions of miriad: ATNF (that is used here) and CARMA. Maybe, the package should be better renamed to "atnf-miriad" to make this clear?
For the issue location: OK, next time I'll use the generic tracker (although I would find that more difficult to manage for all sided).

**Comment by gijzelaerr** [comment]
@olebole i forgot about this issue and found this now while cleaning up. Do you still want this in Debian?

**Comment by olebole** [comment]
I must admit that I don't have a feeling how important that package is; you probably know it better. If it is still in common use, it would be nice to have it, sure. However, I can't do it myself -- I have >130 packages already, and another heavy one is just too much.

**Comment by gijzelaerr** [comment]
I have no idea about usage statistics but for us, it works in its current form. Lets close the issue and reevaluate when we feel the time and/or need.
